### PR TITLE
use firedrakeproject/firedrake for tests

### PR DESCRIPTION
**Pull request by APaganini**

### CODE REVIEW

**Comment by florianwechsung** [comment]
I think I was wrong about this on slack. We are using circle ci now, and that's actually set up in 

`fireshape/.circleci/config.yml`

unfortunately I don't think we can just replace florianwechsung/firedrake with firedrake/firedrake, since my docker image also contains some extra prerequisites such as patchelf, rol, and roltrilinos. I'm not sure how to fix this. I guess we could have an automated system that takes firedrake/firedrake and adds those dependencies, or I'm sure we can somehow add their installation to the circleci test run, but maybe that's not worth the effort...

**Comment by APaganini** [comment]
I see. The easiest thing to do is to create a `fireshape/firedrakefortest` image on dockerhub (to be built at every push in master). This would be very similar to the curent `fireshape/docker/dockerhub/Dockerfile`. In this case, should we keep `fireshape/Dockerfile` ?

**Comment by APaganini** [comment]
Also, I suggest to put move the make lint test to position 1, that it:

```
    steps:
      - checkout
      - run: . /home/firedrake/firedrake/bin/activate; export PYTHONPATH=$(pwd):$PYTHONPATH; make lint
      - run: . /home/firedrake/firedrake/bin/activate; export PYTHONPATH=$(pwd):$PYTHONPATH; make test
      - run: . /home/firedrake/firedrake/bin/activate; export PYTHONPATH=$(pwd):$PYTHONPATH; make examples
```

instead of

```
    steps:
      - checkout
      - run: . /home/firedrake/firedrake/bin/activate; export PYTHONPATH=$(pwd):$PYTHONPATH; make test
      - run: . /home/firedrake/firedrake/bin/activate; export PYTHONPATH=$(pwd):$PYTHONPATH; make examples
      - run: . /home/firedrake/firedrake/bin/activate; export PYTHONPATH=$(pwd):$PYTHONPATH; make lint
```

**Comment by florianwechsung** [comment]
I think we can just delete `fireshape/Dockerfile` and `fireshape/.travis.yml`, since we are only using circle ci these days. having a `fireshape/firedrakefortest` docker sounds image good.

**Comment by APaganini** [comment]
Ok, I'll push `fireshape/firedrakefortest` first separately so that this branch will already take the new test. I'll also remove the unnecessary files.

**Comment by APaganini** [comment]
let me just run the tests once again

**Comment by APaganini** [comment]
@florianwechsung  I think this is ready to go, please have a look

**Review by florianwechsung — APPROVED** [review]

**Comment by florianwechsung** [comment]
This looks good! Merged!

**Pull request merged**
