### PR TITLE
Adding periodic controls and time dependent objectives

### PR DESCRIPTION
**Pull request by medinaeder**
1) In controls.py I have added a new class that enables shape optimization for periodic domains. 
There are a couple of fixes that are needed. One obvious error has to do with the inner product associated with this domain. Using an ElasticInnerProduct fails it probably has to do with the wrong nullspace being computed. You lose the rigid rotation mode in a periodic domain.

2) I have added a new reduced objective class that can handle time dependent problems. The current objective interface is not the cleanest/clearest for time dependent problems. Instead I just compute the objective inside the PDEShapeConstraint and then use a dummy objective function. 

3) Added an example implementation of the time dependent optimization. This example verifies a working implementation of the time reduced objective by solving an elastodynamics problem using Crank-Nicholson time integration.

### CODE REVIEW

**Comment by florianwechsung** [comment]
I like the idea of adding support for time-dependent and also for periodic problems, but I'm a bit confused here. The included example doesn't actually seem to involve a periodic domain and I also don't see anything about the control that makes it periodic either?

**Comment by medinaeder** [comment]
@florianwechsung  Ah sorry! Yes this is for two different features. I couldn't figure out how to split up the features into two branches after I had already submitted them to my own branch. Is there a way splitting the commits into two features? I currently do not have a useful example. 

The regular FEcontrol breaks because the underlying coordinate field is discontinuous. The fix is computing the update and then restricting the update to a CG function and then interpolating that back to the DG coordinates.

**Comment by florianwechsung** [comment]
Okay so if the `PeriodicControlSpace` is not actually being used here anywhere, then let's start by just doing the time dependent objective for now and open a separate PR for the periodic problem. I don't know of the top of my head how to elegantly split a git branch into two. If you don't find anything better on google, you could just make a new branch `transient` and then selectively pick the files from the `periodic` branch that you want , e.g. `git checkout periodic -- examples/timedepedent/PDEconstraint_beam.py `.

Regarding the actual implementation: I think this mostly makes sense, I'm just a bit hazy about why there is a `FakeObjective`? It doesn't do anything, and is not used in `fs.TimeReducedObjective`. You essentially make the assumption that the PDEConstraint now contains the objective as well and use that assumption in `fs.TimeReducedObjective` since you access `e.J`. So why not just get rid of `FakeObjective`?

**Comment by medinaeder** [comment]
I agree with you. I opened a draft pull request for the transient problem.

**Pull request closed without merging**
